version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-test-versioning"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nwoz30810hky"
s3_prefix = "sam-test-versioning"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
